
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-02-02T16:20:38+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "dd611fed687052552d95474c443ccde33b16facf",
 "version": "0+untagged.5.gdd611fe.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
